### ISSUE TITLE
No support for MS Access *.accdb format

### ISSUE THREAD

**Issue by Bodeck** [mlaanderson/database-js-adodb#4]
Hi,
I got following error when try connect ms database with *.accdb extension. If same db is saved as mdb there is no problem with  connection.
`Error: Spawn C:\WINDOWS\SysWOW64\cscript.exe error
    at ChildProcess.<anonymous> (C:\Users\user\Desktop\MyProjects\node-access\node_modules\node-adodb\lib\spawn.js:120:37)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  process: {
    code: -2147467259,
    message: "Unrecognized database format 'C:\\Users\\user\\Desktop\\MyProjects\\gut\\Data_UPS_NL_ADYEN.accdb'."
  },
  exitCode: 0
}`

**Comment by LarryEitel** [comment]
> Hi,
> I got following error when try connect ms database with *.accdb extension. If same db is saved as mdb there is no problem with connection.
> `Error: Spawn C:\WINDOWS\SysWOW64\cscript.exe error at ChildProcess.<anonymous> (C:\Users\user\Desktop\MyProjects\node-access\node_modules\node-adodb\lib\spawn.js:120:37) at ChildProcess.emit (events.js:223:5) at maybeClose (internal/child_process.js:1021:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) { process: { code: -2147467259, message: "Unrecognized database format 'C:\\Users\\user\\Desktop\\MyProjects\\gut\\Data_UPS_NL_ADYEN.accdb'." }, exitCode: 0 }`

@Bodeck Did you ever find a way to connect with accdb? Got a client requesting that I connect to some MSAccess data. Thank You

**Comment by Bodeck** [comment]
@LarryEitel - I have used different package [node-adodb](https://www.npmjs.com/package/node-adodb)
